# Generated by Django 5.2.7 on 2025-10-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0002_crear_grupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='estado',
            field=models.CharField(choices=[('al_dia', 'Al_dia'), ('atrasada', 'Atrasada')], default='atrasada', max_length=10),
        ),
    ]
