# Generated by Django 5.2.7 on 2025-11-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0003_alter_cuota_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='estado_pago',
            field=models.CharField(choices=[('abonada', 'Abonada'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10),
        ),
    ]
