# Generated by Django 5.2.7 on 2025-11-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0004_inscripcion_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Comprobante de pago (PDF, JPG, PNG)', null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='estado',
            field=models.CharField(choices=[('al_dia', 'Al día'), ('atrasada', 'Atrasada'), ('pendiente_revision', 'Pendiente de Revisión')], default='atrasada', max_length=20),
        ),
    ]
