# Generated by Django 5.2.7 on 2025-11-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0005_cuota_comprobante_alter_cuota_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['-periodo_anio', '-periodo_mes', '-fecha_vencimiento']},
        ),
        migrations.AddField(
            model_name='cuota',
            name='inscripciones',
            field=models.ManyToManyField(blank=True, help_text='Inscripciones incluidas en esta cuota', related_name='cuotas', to='sis_app.inscripcion'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='periodo_anio',
            field=models.IntegerField(blank=True, help_text='Año del período', null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='periodo_mes',
            field=models.IntegerField(blank=True, help_text='Mes del período (1-12)', null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, help_text='Pesos Argentinos (cuota social)', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='cuota',
            unique_together={('usuario_socio', 'periodo_mes', 'periodo_anio')},
        ),
    ]
