# Generated by Django 5.2.7 on 2025-11-09 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0006_alter_cuota_options_cuota_inscripciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='sis_app.actividad'),
        ),
    ]
