services:
  mysql:
    image: mysql:8.0
    container_name: mysql-sis-django
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sis-django-db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-sis-django
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data: